version: '3.8'

services:
  postgresql:
    image: postgres
    restart: always
    ports:
      - '5433:5432'
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

  rabbitmq:
    image: rabbitmq:3.10.7-management
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"

volumes:
  postgresql_data:
    driver: local